java_library(
  name = 'sample',
  sources = globs(
    'app/*.java',
    'resource/*.java',
    'config/*.java',
    'protocol/*.java',
  ),
  dependencies = [
    '3rdparty/java/io/dropwizard:dropwizard-core',
    '3rdparty/java/io/dropwizard:dropwizard-testing',
  ],
  resources = [
    'src/main/resources'
  ]
)
