java_library(
  name = 'sample',
  sources = globs(
    'app/*.java',
    'resource/*.java',
    'config/*.java'
  ),
  dependencies = [
    '3rdparty/java/io/dropwizard:dropwizard-core'
  ],
  resources = [
    'src/main/resources'
  ]
)
